#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 27 08:01:01 2022

@author: monserratlopez
"""
import matplotlib.pyplot as plt

a = [1,2,3,4]
b =[11,22,33,44]

plt.plot(a,b, color = 'blue', linewidth = 3, label = 'linea')
plt.legend()
plt.show() 
