#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 27 08:25:48 2022

@author: monserratlopez
"""
#Grafico simple con plot
import matplotlib.pyplot as plt

a = [3,4,5,6]
b = [5,6,3,4]

plt.plot(a,b)

plt.show()