#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Jul 27 08:31:18 2022

@author: monserratlopez
"""
#-------Diagrama de Lineas---------
import matplotlib.pyplot as plt
#Definir los datos
x1 = [3,4,5,6] 
y1 = [5,6,3,4]
x2 = [2,5,8]
y2 = [3,4,3] 

#Configurar las características del gráfico

plt.plot(x1,y1, label = 'Linea 1', linewidth = 4, color = 'blue')	
plt.plot(x2,y2, label = 'Linea 2', linewidth = 4, color = 'green')	
plt.title('Diagrama de Líneas')
plt.ylabel('Eje Y')
plt.xlabel('Eje x')

#Mostrar leyenda cuadricula y figura

plt.legend()
plt.grid()
plt.show()